# global config
global:
  scrape_interval: 1m      # Default is every 1 minute.
  evaluation_interval: 1m  # Evaluate rules every 15 seconds. Default is every 1 minute.
  scrape_timeout: 59s      # Default is (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "rpi-metrics"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["192.168.30.5:9100"]
        labels:
          location: "shed"
      - targets: ["192.168.30.8:9100"]
        labels:
          location: "stagewall"
      - targets: ["192.168.30.9:9100"]
        labels:
          location: "lower schoolroom"
